project_id = "rdcwcfucghobizebzodz"

[functions.check-owner]
verify_jwt = false

[functions.start-trial]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.enhanced-extract]
verify_jwt = false
